In [1]:
import tweepy as tw
from tqdm import tqdm
import pandas as pd
import os
import datetime
import re

In [2]:
api_key = ''
api_secret_key = ''
bearer_token = ''
access_token = ''
access_token_secret = ''

In [3]:
auth = tw.OAuthHandler(api_key, api_secret_key)
auth.set_access_token(access_token, access_token_secret)
api = tw.API(auth, wait_on_rate_limit=True)

In [4]:
# Define the search term and the date_since date as variables
search_words = "woolworths australia"

# Collect tweets
tweets = tw.Cursor(
              api.search,
              tweet_mode='extended',
              retweeted_status='full_text',
              q=search_words,
              lang="en",
                    ).items(10000)

# tweets = tw.Cursor(
#               api.search,
#               tweet_mode='extended',
#               retweeted_status='full_text',
#               q=search_words,
#               lang="en",
#               since=date_since
#                     ).items(NUM_TWEETS)

In [5]:
try:
    del df
except:
    pass

In [6]:
for tweet in tqdm(tweets):
    t = tweet
    d = {}
    d['author_follower_count'] = [tweet.author.followers_count]
    d['author_friends_count'] = [tweet.author.friends_count]
    d['author_listed_count'] = [tweet.author.listed_count]
    d['author_favourites_count'] = [tweet.author.favourites_count]
    d['user'] = [tweet.author.name]
    d['author_screen_name'] = [tweet.author.screen_name]
    d['author_location'] = [tweet.author.location]
    d['author_created_at'] = [tweet.author.created_at]
    
    try:
        d['full_text'] = [re.sub('&amp;','and', re.sub('https:\/\/t\.co\/.{10}','',tweet.retweeted_status.full_text))]
    except AttributeError:  # Not a Retweet
        d['full_text'] = [re.sub('&amp;','and', re.sub('https:\/\/t\.co\/.{10}','', tweet.full_text))]
    d['length'] = [len(d['full_text'])]
    d['created_at'] = [tweet.created_at.strftime('%Y-%m-%d %H:%M')]
    d['hashtags'] = [','.join([i['text'] for i in t.entities['hashtags']])]
    d['user_mentions'] = [','.join([i['name'] for i in tweet.entities['user_mentions']])]
    d['num_user_mentions'] = [len(tweet.entities['user_mentions'])]
    d['source'] = [tweet.source]
    d['retweet_count'] = [tweet.retweet_count]
    d['favorite_count'] = [tweet.favorite_count]
    d['geo'] = [tweet.geo]
    d['coordinates'] = [tweet.coordinates]
    d['place'] = [tweet.place]
    d['contributors'] = [tweet.contributors]
    d['search_term'] = ['costco australia']

    try:
        df = pd.concat([df, pd.DataFrame.from_dict(d)], ignore_index=True)
    except:
        df = pd.DataFrame.from_dict(d)

160it [00:16,  9.62it/s]

In [7]:
df.head()

,author_follower_count,author_friends_count,author_listed_count,author_favourites_count,user,author_screen_name,author_location,author_created_at,full_text,length,...,user_mentions,num_user_mentions,source,retweet_count,favorite_count,geo,coordinates,place,contributors,search_term
0,81,0,0,32,I'm All News,ImAllNews,,2018-05-02 10:52:01,sunriseon7: RT @7NewsSydney: NSW Coronavirus U...,1,...,"7NEWS Sydney,Gladys Berejiklian",2,IFTTT,0,0,None,None,None,None,costco australia
1,5,133,0,3,Tony Sun,ala_ZhiyuanSun,,2017-10-24 01:56:32,"NSW Coronavirus Update: ""Overnight, as predict...",1,...,"7NEWS Sydney,Gladys Berejiklian",2,Twitter for iPhone,11,0,None,None,None,None,costco australia
2,1425,1281,3,141794,Helen Jacobsen #SaveThePowerhouse #COVIDisAirb...,helen_it,Wisconsin,2009-09-09 00:20:44,"""In light of recent community transmission in ...",1,...,7NEWS Sydney,1,Twitter Web App,6,0,None,None,None,None,costco australia
3,41,7,0,0,Diversity-Index Australia,divIndex_AU,sydney,2020-11-13 02:43:24,Woolworths Group \n@woolworths \n leadership d...,1,...,"Woolworths,ASX üèõ The heart of Australia's fina...",2,Twitter Web App,0,0,None,None,None,None,costco australia
4,2510,1203,123,58979,Michael Brown,MJIBrown,"Melbourne, Australia",2013-07-07 23:24:08,"@glengyron @patstokes Actually, what may be mo...",1,...,"Glengyron,Patrick Stokes",2,Twitter for iPhone,0,3,None,None,None,None,costco australia

In [51]:
# for block in api.trends_place(1105779)[0]['trends']:
#     print(block['name'])

In [50]:
# api.trends_available()

In [239]:
t.contributors

In [26]:
df['search_term'].unique()

array(['woolworths australia', 'coles australia', 'IGA australia',
       'supermarket australia', 'groceries australia', 'costco australia'],
      dtype=object)

In [81]:
len(df)

155

In [82]:
df.head()

,author_follower_count,author_friends_count,author_listed_count,author_favourites_count,user,author_screen_name,author_location,author_created_at,full_text,length,...,user_mentions,num_user_mentions,source,retweet_count,favorite_count,geo,coordinates,place,contributors,search_term
0,777,857,4,23702,david mccarthy,DavidDmacca,"Melbourne, Victoria",2012-02-03 08:55:38,"OMG the @bp_Australia on Sydney road , Coburg ...",1,...,"bp Australia,Woolworths",2,Twitter for iPhone,0,1,None,None,None,None,costco australia
1,18,146,0,10,Sabrina hill,Sabrina46554824,United States,2021-06-08 06:08:04,Woolworths gift card code for Australia.#Woolw...,1,...,,0,Twitter Web App,0,1,None,None,None,None,costco australia
2,760,0,5,1,PFD Bot,pfdbot,"Anchorage, AK",2017-09-08 05:07:29,"Alaskans own 119,227 shares of Woolworths Grou...",1,...,,0,pfdbot,0,0,None,None,None,None,costco australia
3,2062,1716,55,10090,David Inderias,d_inderias,"Brisbane, Queensland",2017-01-16 04:58:45,@Mryoungy87 @woolworths @applesnpearsAU @Fresh...,1,...,"Youngy ‚ìã,Woolworths,APAL,Fresh Supply Co.",4,Twitter for iPhone,0,0,None,None,Place(_api=<tweepy.api.API object at 0x0000023...,None,costco australia
4,62,393,2,542,Donna Dormitorio,DonnaDorm,,2014-09-05 07:24:53,Supermarkets will remain open during a lockdow...,1,...,,0,Twitter for iPhone,0,0,None,None,None,None,costco australia

In [83]:
df.to_csv('data/woolworths.csv', index=False)

In [172]:
print(df.iloc()[0]['full_text'])
# df.iloc()[0]['hashtags']
#gonna need to remove &amp;

While @woolworths is Australia's #1 retailer, they are looking to become a household name in Asia #AroundTheWorld #ATWCreativity https://t.co/DOSLkHcQum

In [98]:
#Useful information about the author
test.author.followers_count
test.author.friends_count
test.author.listed_count
test.author.favourites_count
test.author.name
test.author.screen_name
test.author.location
test.author.created_at

#Useful information about the tweet
test.full_text
test.created_at
test.entities['hashtags']
test.entities['user_mentions']
test.source
test.retweet_count
test.favorite_count
test.geo
test.coordinates
test.place
test.contributors

datetime.datetime(2016, 5, 31, 8, 2, 53)